'use client';
import { useState } from 'react';
import Link from 'next/link';
import styles from './CourseDetail.module.css';

export default function CourseDetail({ course }) {
    const [openModule, setOpenModule] = useState(0);

    const toggle = (i) => {
        setOpenModule(openModule === i ? -1 : i);
    };

    const downloadSyllabus = () => {
        // Create a script to load html2pdf from CDN
        const script = document.createElement('script');
        script.src = 'https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js';
        script.onload = () => {
            // Create HTML content for PDF
            const element = document.createElement('div');
            element.style.padding = '40px';
            element.style.fontFamily = 'Arial, sans-serif';
            element.style.color = '#333';
            element.innerHTML = `
                <div style="text-align: center; margin-bottom: 40px; border-bottom: 3px solid #8861FF; padding-bottom: 20px;">
                    <h1 style="color: #8861FF; margin: 0; font-size: 28px;">${course.title}</h1>
                    <p style="margin: 10px 0; color: #666; font-size: 14px;">Urblearn Course Syllabus</p>
                </div>
                
                <div style="margin-bottom: 30px;">
                    <h3 style="color: #8861FF; margin-bottom: 10px;">Course Overview</h3>
                    <p style="line-height: 1.8; color: #555; margin: 0;">${course.desc}</p>
                </div>
                
                <div style="margin-bottom: 20px; padding: 15px; background: #f5f5f5; border-radius: 8px;">
                    <table style="width: 100%; font-size: 13px;">
                        <tr>
                            <td style="padding: 8px;"><strong>Duration:</strong></td>
                            <td>${course.duration}</td>
                            <td style="padding: 8px;"><strong>Modules:</strong></td>
                            <td>${course.modules}</td>
                        </tr>
                        <tr>
                            <td style="padding: 8px;"><strong>Course Fee:</strong></td>
                            <td>${course.price}</td>
                            <td style="padding: 8px;"><strong>Rating:</strong></td>
                            <td>⭐ ${course.rating}</td>
                        </tr>
                    </table>
                </div>
                
                <div style="margin-bottom: 30px; page-break-inside: avoid;">
                    <h3 style="color: #8861FF; margin-bottom: 20px; border-bottom: 2px solid #e0d4ff; padding-bottom: 10px;">Course Syllabus</h3>
                    ${course.syllabus.map((mod) => `
                        <div style="margin-bottom: 18px; page-break-inside: avoid;">
                            <h4 style="color: #333; margin: 0 0 10px 0; font-size: 14px;">${mod.module}. ${mod.title}</h4>
                            <ul style="margin: 0; padding-left: 20px; color: #555; font-size: 12px; line-height: 1.8;">
                                ${mod.topics.map((topic) => `<li>${topic}</li>`).join('')}
                            </ul>
                        </div>
                    `).join('')}
                </div>
                
                <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #e0d4ff; font-size: 12px; color: #999; text-align: center;">
                    <p>Generated by Urblearn | www.urblearn.com</p>
                </div>
            `;
            
            // Generate PDF
            const opt = {
                margin: 10,
                filename: `${course.title.replace(/\s+/g, '-').toLowerCase()}-syllabus.pdf`,
                image: { type: 'jpeg', quality: 0.98 },
                html2canvas: { scale: 2 },
                jsPDF: { orientation: 'portrait', unit: 'mm', format: 'a4' }
            };
            
            html2pdf().set(opt).from(element).save();
        };
        document.head.appendChild(script);
    };

    return (
        <>
            {/* ===== HERO SECTION ===== */}
            <section className={styles.hero}>
                <div className={styles.heroBg}></div>
                <div className={styles.heroContent}>
                    <div className={styles.heroText}>
                        <div className={styles.badges}>
                            <span className={styles.liveBadge}>
                                <span className={styles.liveDot}></span> LIVE Course
                            </span>
                            <span className={styles.tagBadge}>{course.tag}</span>
                        </div>
                        <h1>{course.title}</h1>
                        <p className={styles.heroSubtitle}>{course.subtitle}</p>
                        <p className={styles.heroDesc}>{course.desc}</p>

                        <div className={styles.statsRow}>
                            <div className={styles.stat}>
                                <span className={styles.statValue}>⭐ {course.rating}</span>
                                <span className={styles.statLabel}>Rating</span>
                            </div>
                            <div className={styles.statDivider}></div>
                            <div className={styles.stat}>
                                <span className={styles.statValue}>{course.modules}</span>
                                <span className={styles.statLabel}>Modules</span>
                            </div>
                            <div className={styles.statDivider}></div>
                            <div className={styles.stat}>
                                <span className={styles.statValue}>{course.duration}</span>
                                <span className={styles.statLabel}>Duration</span>
                            </div>
                            <div className={styles.statDivider}></div>
                            <div className={styles.stat}>
                                <span className={styles.statValue}>{course.students}</span>
                                <span className={styles.statLabel}>Students</span>
                            </div>
                        </div>

                        <div className={styles.heroCta}>
                            <Link href={`/enroll/${course.slug}`} className={styles.enrollBtn}>Enroll Now — {course.price}</Link>
                            <button className={styles.demoBtn}>Book Free Demo</button>
                        </div>
                    </div>
                    <div className={styles.heroImage}>
                        <img src={course.image} alt={course.title} />
                        <div className={styles.priceCard}>
                            <span className={styles.priceLabel}>Course Fee</span>
                            <span className={styles.priceValue}>{course.price}</span>
                            <span className={styles.priceNote}>EMI Available</span>
                        </div>
                    </div>
                </div>
            </section>

            {/* ===== HIGHLIGHTS BAR ===== */}
            <section className={styles.highlights}>
                <div className={styles.highlightsInner}>
                    {course.highlights.map((h, i) => (
                        <div key={i} className={styles.highlightItem}>
                            <span className={styles.highlightIcon}>✓</span>
                            <span>{h}</span>
                        </div>
                    ))}
                </div>
            </section>

            {/* ===== LIVE + 1:1 BANNER ===== */}
            <section className={styles.liveBanner}>
                <div className={styles.liveBannerInner}>
                    <div className={styles.liveBannerCard}>
                        <div className={styles.liveBannerIcon}>🔴</div>
                        <div>
                            <h3>100% Live Classes</h3>
                            <p>Learn in real-time with expert instructors. Ask questions, get instant feedback, and collaborate with peers.</p>
                        </div>
                    </div>
                    <div className={styles.liveBannerCard}>
                        <div className={styles.liveBannerIcon}>👤</div>
                        <div>
                            <h3>1:1 Mentorship Sessions</h3>
                            <p>Get personalized guidance from industry experts. Dedicated sessions for doubt clearing, career advice, and project reviews.</p>
                        </div>
                    </div>
                    <div className={styles.liveBannerCard}>
                        <div className={styles.liveBannerIcon}>📜</div>
                        <div>
                            <h3>Certificate & Placement</h3>
                            <p>Earn an industry-recognized certificate and get placement assistance with resume building and mock interviews.</p>
                        </div>
                    </div>
                </div>
            </section>

            {/* ===== SYLLABUS ===== */}
            <section className={styles.syllabus}>
                <div className={styles.syllabusInner}>
                    <div className={styles.syllabusHeader}>
                        <div className={styles.syllabusTitle}>
                            <h2>Course <span>Syllabus</span></h2>
                            <p>{course.modules} modules · {course.duration} of structured learning</p>
                        </div>
                        <button className={styles.downloadBtn} onClick={downloadSyllabus}>
                            📥 Download Syllabus
                        </button>
                    </div>
                    <div className={styles.syllabusGrid}>
                        {course.syllabus.map((mod, i) => (
                            <div
                                key={i}
                                className={`${styles.syllabusCard} ${openModule === i ? styles.syllabusCardOpen : ''}`}
                                onClick={() => toggle(i)}
                            >
                                <div className={styles.syllabusCardHeader}>
                                    <div className={styles.moduleNumber}>{mod.module}</div>
                                    <h3>{mod.title}</h3>
                                    <span className={styles.chevron}>{openModule === i ? '−' : '+'}</span>
                                </div>
                                <div className={styles.syllabusCardBody}>
                                    <ul>
                                        {mod.topics.map((topic, j) => (
                                            <li key={j}>
                                                <span className={styles.topicDot}></span>
                                                {topic}
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* ===== KEY FEATURES ===== */}
            <section className={styles.features}>
                <div className={styles.featuresInner}>
                    <h2>Why Choose This <span>Course</span></h2>
                    <div className={styles.featuresGrid}>
                        {course.features.map((f, i) => (
                            <div key={i} className={styles.featureCard}>
                                <span className={styles.featureIcon}>{f.icon}</span>
                                <p>{f.text}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* ===== CTA ===== */}
            <section className={styles.cta}>
                <div className={styles.ctaInner}>
                    <h2>Ready to Start Your Journey?</h2>
                    <p>Join {course.students} students already learning. Limited seats for live batches.</p>
                    <div className={styles.ctaActions}>
                        <Link href={`/enroll/${course.slug}`} className={styles.enrollBtn}>Enroll Now — {course.price}</Link>
                        <button className={styles.demoBtn}>Book Free Demo Class</button>
                    </div>
                </div>
            </section>
        </>
    );
}
